### ISSUE TITLE
Re-design app architecture and implement

### ISSUE THREAD

**Issue by cskime** [cskime/UIKit-Viewer#17]
Re-design app architecture

- In this project, there's no DB and server communication. It's very simple app.
- I think i don't need use cases. It's necessary to make more smaller and simpler.
- So, i'll design architecture based on VIP pattern. There will be VIP component and Entities only.
- Interactor will use Entities directly because it doesn't need infras.

## Todos

- [x] Design the home module
- [ ] Implement home module
- [ ] Design the preview module
- [ ] Implement preview module
